name: pre-commit

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  pre-commit:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: 3.8.10
    - name: Install packages
      run: pip install pre-commit==3.2.2 black==23.3.0 isort==5.12.0
    - name: Check-code
      run: make check-code
